version: '3.9'

services:
  database:
    image: postgres
    restart: always
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
        # Desde fuera accedo por el puerto 5433
        # Desde dentro accedo por el puerto 5432
      - '5433:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data

  api:
    container_name: api
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      # Puerto interno
      DB_PORT: 5432
      DB_NAME: todo
      DB_HOST: database
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: always
